/**
 * Bitácora Auditare — feed cronológico.
 * REGLA: las entradas nuevas van AL PRINCIPIO del array (más reciente arriba).
 * at = fecha/hora ISO con zona -03:00 (Uruguay).
 */
window.BITACORA_CHANGELOG = [
  {
    at: "2026-08-28T12:42:00-03:00",
    module: "Accesos",
    moduleHref: "propuestas/accesos.html",
    title: "Empresas primero, contratistas al desplegar",
    status: "done",
    details: [
      "La lista muestra cada empresa contratante plegada (FIMSA, COFUSA, UPM)",
      "Al abrir una empresa se ven sus contratistas, con usuario, PIN y Otorgar / Revocar",
      "Si no hay contratistas, el bloque lo dice",
    ],
  },
  {
    at: "2026-08-28T12:41:00-03:00",
    module: "Accesos",
    moduleHref: "propuestas/accesos.html",
    title: "Raya en el menú que lo separa del resto",
    status: "done",
    details: [
      "En la sidebar, Accesos queda debajo de una línea fina",
      "El resto de pestañas (Tablero a Informes) sigue agrupado arriba",
    ],
  },
  {
    at: "2026-08-28T12:40:00-03:00",
    module: "Calendarios",
    moduleHref: "propuestas/calendarios.html",
    title: "Filtro por mes y contratista de la empresa elegida",
    status: "done",
    details: [
      "Solo se listan contratistas de la contratante activa que brindaron servicio en ese mes",
      "El desplegable de contratista y los informes siguen el mismo recorte",
      "Quien no tuvo servicio en el período no aparece (p. ej. Forestal Arapey en FIMSA)",
    ],
  },
  {
    at: "2026-08-25T08:59:00-03:00",
    module: "Tablero",
    moduleHref: "propuestas/tablero.html",
    title: "Se quitó la franja de cinco fases de todas las pantallas",
    status: "done",
    details: [
      "Ya no aparece debajo de la barra superior en Tablero, Documentos, Calendarios, Solicitudes, Revisión ni Informes",
      "El ciclo se sigue en las columnas del tablero Kanban",
    ],
  },
  {
    at: "2026-08-24T18:52:00-03:00",
    module: "Tablero",
    moduleHref: "propuestas/tablero.html",
    title: "El ciclo se sigue en un tablero Kanban de cinco columnas",
    status: "done",
    details: [
      "Cada contratista es una tarjeta: Entrega, Control, Primer informe, Rectificación y Segundo informe",
      "Se puede arrastrar la tarjeta o moverla desde el detalle",
      "Al abrir un contratista se ven entrega, pendientes, observaciones, personal, vehículos y documentos en revisión",
    ],
  },
  {
    at: "2026-08-24T18:32:00-03:00",
    module: "Empresas",
    moduleHref: "propuestas/empresas.html",
    title: "El auditor elige la empresa contratante antes de ver el ciclo",
    status: "done",
    details: [
      "Después del ingreso se abre la lista de empresas (FIMSA y COFUSA en la demo)",
      "Al entrar a una empresa, Tablero, Documentos, Calendarios, Solicitudes, Revisión e Informes muestran solo sus contratistas",
      "Desde la barra superior se puede cambiar de empresa sin salir de la sesión",
    ],
  },
  {
    at: "2026-08-15T21:50:00-03:00",
    module: "Comercial",
    moduleHref: "propuestas/comercial.html",
    title: "Prototipo publicado para que el cliente lo recorra",
    status: "done",
    details: [
      "Demo en vivo: https://auditare.vercel.app/",
      "Usuario: rosina@auditare.uy",
      "Contraseña: papa2026",
    ],
  },
  {
    at: "2026-08-15T21:35:00-03:00",
    module: "Tablero",
    moduleHref: "propuestas/tablero.html",
    title: "Al ingresar, el ícono de Auditare vuela del centro a la sidebar",
    status: "done",
    details: [
      "Después del login el ícono ocupa el centro de la pantalla",
      "Luego se achica y se coloca en el logo de la barra lateral",
    ],
  },
  {
    at: "2026-08-15T19:30:00-03:00",
    module: "Tablero",
    moduleHref: "propuestas/tablero.html",
    title: "El auditor entra por una pantalla de ingreso corporativa",
    status: "done",
    details: [
      "La app abre en /login con el ícono blanco de Auditare sobre el panel plum",
      "Con correo y clave de demostración se entra al tablero; sin sesión no se ve el ciclo",
      "Desde la barra superior se puede cerrar la sesión y volver al ingreso",
    ],
  },
  {
    at: "2026-08-15T12:38:00-03:00",
    module: "Comercial",
    moduleHref: "propuestas/comercial.html",
    title: "Propuesta de implementación y mantenimiento del sistema",
    status: "proposal",
    details: [
      "Implementación USD 10.000: tres perfiles, ciclo de auditoría, documentos, revisión e informes",
      "Mantenimiento USD 100 por mes: soporte, corrección de errores y actualizaciones de seguridad",
      "Pago de la implementación en dos cuotas iguales: 50 % al inicio y 50 % al cierre",
    ],
  },
  {
    at: "2026-08-15T12:36:00-03:00",
    module: "Operarios",
    moduleHref: "propuestas/operarios.html",
    title: "Al clicar el rostro se ven cédula y libreta, una al lado de la otra",
    status: "done",
    details: [
      "La foto del padrón es la recortada del documento, no un retrato genérico",
      "El visor abre en dos columnas: Cédula de identidad y Libreta de conducir",
      "En la libreta se muestran frente y dorso, con el vencimiento del reverso",
    ],
  },
  {
    at: "2026-08-15T12:30:00-03:00",
    module: "Operarios",
    moduleHref: "propuestas/operarios.html",
    title: "La libreta guarda el vencimiento del dorso y se puede abrir completa",
    status: "done",
    details: [
      "El padrón toma la fecha “válido hasta” del reverso de la libreta",
      "Al clicar la columna de libreta se ve frente y dorso del permiso",
    ],
  },
  {
    at: "2026-08-15T12:25:00-03:00",
    module: "Operarios",
    moduleHref: "propuestas/operarios.html",
    title: "Al clicar la foto se abre la cédula completa",
    status: "done",
    details: [
      "En Documentos → Funcionarios, la foto del padrón abre un visor a pantalla",
      "Se muestra el frente y dorso de la C.I. del funcionario, con nombre y número",
    ],
  },
  {
    at: "2026-08-15T11:50:00-03:00",
    module: "Operarios",
    moduleHref: "propuestas/operarios.html",
    title: "El funcionario carga C.I., carné y libreta desde su propio portal",
    status: "done",
    details: [
      "Hay una pantalla de carga en /funcionario: se identifica con la cédula y la empresa",
      "Sube PDF o foto de cámara de los tres documentos y confirma las fechas de vencimiento",
      "El padrón del auditor (Documentos → Funcionarios) muestra la foto recortada de la C.I. y las tres vigencias",
    ],
  },
  {
    at: "2026-08-15T11:32:00-03:00",
    module: "Bitácora",
    moduleHref: "index.html",
    title: "La bitácora usa la marca Auditare (A con check)",
    status: "done",
    details: [
      "El menú lateral deja la letra A y muestra el ícono blanco",
      "El encabezado de cada página lleva la misma marca sobre el degradé burgundy",
      "El favicon de la bitácora pasa a ser esa marca",
    ],
  },
  {
    at: "2026-08-15T11:29:00-03:00",
    module: "Tablero",
    moduleHref: "propuestas/tablero.html",
    title: "La marca de la sidebar queda en blanco, sin el recuadro negro",
    status: "done",
    details: [
      "Hay una versión blanca de la A con check, en SVG y PNG, con fondo transparente",
      "El menú lateral usa esa marca sobre el plum, sin el borde negro del lockup original",
    ],
  },
  {
    at: "2026-08-15T11:19:00-03:00",
    module: "Tablero",
    moduleHref: "propuestas/tablero.html",
    title: "La sidebar y el favicon usan la marca Auditare (A con check)",
    status: "done",
    details: [
      "El menú lateral (escritorio y móvil) muestra el ícono junto al nombre Auditare",
      "El favicon de la app pasa a ser esa misma marca, sin el texto del lockup",
    ],
  },
  {
    at: "2026-08-15T11:01:00-03:00",
    module: "Bitácora",
    moduleHref: "index.html",
    title: "La bitácora pasa a llamarse Bitácora Auditare",
    status: "done",
    details: [
      "El wordmark del encabezado y el menú lateral quedan Auditare",
      "La marca de la sidebar pasa de R a A",
      "El pie de todas las páginas dice Bitácora · Auditare",
    ],
  },
  {
    at: "2026-08-15T10:58:00-03:00",
    module: "Fases",
    moduleHref: "propuestas/fases.html",
    title: "Arranca la fase 1: diseño y maquetación de la interfaz",
    status: "progress",
    details: [
      "El desarrollo queda organizado en cuatro fases: Inicio, Backend, Prueba y Producción",
      "Fase 1 (en curso): maquetación y diseño UI de las pantallas del auditor",
      "Siguen: cableado del backend, prueba en uso directo, y salida a producción con soporte",
    ],
  },
  {
    at: "2026-08-15T10:56:00-03:00",
    module: "Calendarios",
    moduleHref: "propuestas/calendarios.html",
    title: "Al clicar un mes se ven los contratistas y los informes de ese período",
    status: "done",
    details: [
      "Cada mes de la lista abre el detalle del período debajo de la tabla",
      "Se listan todos los contratistas asociados a ese calendario",
      "Los informes quedan filtrados por el mes elegido; septiembre (borrador) muestra el vacío",
    ],
  },
  {
    at: "2026-08-15T10:55:00-03:00",
    module: "Tablero",
    moduleHref: "propuestas/tablero.html",
    title: "El wordmark de la sidebar pasa de Rosina a Auditare",
    status: "done",
    details: [
      "El nombre en el menú lateral (escritorio y móvil) queda Auditare",
      "El pie sigue diciendo Auditorías P.A.P.A.",
    ],
  },
  {
    at: "2026-08-15T10:52:00-03:00",
    module: "Documentos",
    moduleHref: "propuestas/documentos.html",
    title: "Documentos pasa al segundo lugar de la sidebar, debajo de Tablero",
    status: "done",
    details: [
      "El menú del auditor queda: Tablero, Documentos, Calendarios, Solicitudes, Revisión e Informes",
    ],
  },
  {
    at: "2026-08-15T10:50:00-03:00",
    module: "Documentos",
    moduleHref: "propuestas/documentos.html",
    title: "Tab Documentos con tres frentes: empresa, vehículos y funcionarios",
    status: "done",
    details: [
      "La sidebar del auditor suma Documentos y deja de mostrar Operarios y Vehículos como tabs sueltos",
      "Adentro hay tres pestañas: Contratista/empresa, Vehículos y Funcionarios",
      "Los padrones de flota y personal se reutilizan; las rutas viejas redirigen al frente que corresponde",
    ],
  },
  {
    at: "2026-08-15T10:45:00-03:00",
    module: "Calendarios",
    moduleHref: "propuestas/calendarios.html",
    title: "Fases del ciclo sin siglas: ENTREGA, CONTROL, RECTIFICACIÓN e INFORME FINAL",
    status: "done",
    details: [
      "La línea de tiempo, los badges y las tablas dejan de mostrar IED–FED, ICD–FCD, IRD–FRD e ICFD–FCFD",
      "La cuarta ventana pasa a llamarse INFORME FINAL en lugar de control final",
      "El cambio queda aplicado en Tablero, Calendarios, Solicitudes, Revisión y la documentación del producto",
    ],
  },
  {
    at: "2026-08-14T10:04:00-03:00",
    module: "Bitácora",
    moduleHref: "index.html",
    title: "Hub de seguimiento de implementaciones",
    status: "done",
    details: [
      "Sitio estático con feed cronológico, sidebar por módulo y publicación en GitHub Pages",
      "Paleta cream, burgundy, plum, tan y sage; tipografía Fraunces y Source Sans 3",
      "Cada avance del sistema se registra acá y queda visible en el hub",
    ],
  },
  {
    at: "2026-08-14T10:00:00-03:00",
    module: "Tablero",
    moduleHref: "propuestas/tablero.html",
    title: "Tabs del ciclo P.A.P.A. con datos de prueba",
    status: "done",
    details: [
      "El auditor recorre Tablero, Calendarios, Solicitudes, Revisión, Operarios, Vehículos e Informes",
      "Cada pantalla muestra el alcance del tab con indicadores y listas de ejemplo",
      "Sirve para recorrer el ciclo completo antes de conectar datos reales",
    ],
  },
  {
    at: "2026-08-14T09:50:00-03:00",
    module: "Tablero",
    moduleHref: "propuestas/tablero.html",
    title: "Shell del auditor con paleta y tipografía del sistema",
    status: "done",
    details: [
      "Menú lateral plum, wordmark Rosina y pie Auditorías P.A.P.A.",
      "Colores tomados de la paleta: cream, tan, burgundy, plum, sage y mauve",
      "Títulos en Fraunces y cuerpo en Source Sans 3",
    ],
  },
  {
    at: "2026-08-14T09:40:00-03:00",
    module: "Informes",
    moduleHref: "propuestas/informes.html",
    title: "Exportación PDF del Resumen Rectificado",
    status: "proposal",
    details: [
      "El cierre del ciclo para el cliente se entrega como Resumen Rectificado en PDF",
      "El informe individual a cada contratista también podrá exportarse",
      "Queda fuera de la primera entrega de pantallas",
    ],
  },
  {
    at: "2026-08-14T09:30:00-03:00",
    module: "Calendarios",
    moduleHref: "propuestas/calendarios.html",
    title: "Avisos automáticos por correo",
    status: "proposal",
    details: [
      "Recordatorio a cada contratista de la fecha límite para enviar documentos",
      "Canal: correo, disparado según las ventanas del calendario activo",
      "Complementa el seguimiento manual del ciclo",
    ],
  },
];
